name: Example deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Deploying!"
          echo "Deployed to Dev environment!"
      
  deploy-staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Deploying!"
          echo "Deployed to Staging environment!"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Deploying!"
          echo "Deployed to Production environment!"
