name: Example deployment

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  deploy-dev:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: Development
      
  deploy-staging:
    needs: deploy-dev
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: Staging

  deploy-prod:
    needs: deploy-staging
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: Production